배너 퍼블리싱
Team-return/JOBIS-DSM-ADMIN-FE pull request #39
Opened 2024-02-21 10:42 UTC by dnjsdmswl

## 특이사항
- 배너 퍼블리싱

## 관련 이슈

- resolved # <!-- 이슈번호  #38

2024-02-21 12:16 UTC, eejx0 approved these changes

2024-02-23 08:52 UTC, JJIIIINN commented on src/Components/Banner/index.tsx
> +				<_.BannerImg src={banner} />
p2) Array.form으로 하는 게 더 좋아보여요.

2024-02-23 08:52 UTC, JJIIIINN commented on src/Components/CreateBanner/index.tsx
> +						<_.TempleteImg src={banner} />
p2) 위와 같음.

2024-02-23 08:53 UTC, JJIIIINN commented
p1) 전체적으로 디자인 시스템을 안 쓰고 있는데 한 번 써보면 좋을 것 같아요.

2024-02-23 08:56 UTC, JJIIIINN commented on src/Components/Banner/index.tsx
> +				<_.BannerImg src={banner} />
배너가 다 다르다면 따로 constant 폴더에 파일 하나 만들고 그 파일에서 배열로 관리하면 좋을 것 같아요.
그걸 import 해서 map으로 돌리면 유지보수적으로도 좋아요.

2024-02-25 04:22 UTC, jikwan0327 requested changes

2024-02-25 04:22 UTC, jikwan0327 commented on src/router.tsx
> +			},
위의 이름도 잘못 되었지만 원래 path 네이밍은 대문자가 들어가면 안됩니다. 또한 소문자로만 구성하며 구분자로 사용할 때에는 하이픈(-)을 사용하는 것이 좋아요. 
참고 글이니 확인해보세요
https://velog.io/@caesars000/RESTful-API-%EA%B0%80%EC%9D%B4%EB%93%9C

2024-03-11 10:35 UTC, parkuiery approved these changes

2024-03-11 10:38 UTC, merged