공지사항 api 연동
Team-return/JOBIS-DSM-ADMIN-FE pull request #48
Opened 2024-05-12 13:58 UTC by eejx0

## 특이사항
공지사항 api 연동

## 관련 이슈

- resolved #45

2024-05-13 00:18 UTC, jikwan0327 requested changes

2024-05-13 00:18 UTC, jikwan0327 commented on src/Apis/Files/index.ts
> +                type: "EXTENSION_FILE",
인자로 type을 받는듯한데 이 type은 어디에서 사용하나요?

2024-05-13 00:18 UTC, jikwan0327 commented on src/Apis/Files/response.ts
> +    }[]
response 값 바뀐게 맞는지 다시 한번 확인해주세요

2024-05-13 00:18 UTC, jikwan0327 commented on src/Apis/Notices/index.ts
> +                console.error("notice write error:", error.message);
에러는 console 말고 토스트를 사용합시다

2024-05-13 00:18 UTC, jikwan0327 commented on src/Apis/Notices/index.ts
> +}
useQuery를 사용하지 않고 이렇게 구현한 이유가 있을까요?

2024-05-13 00:18 UTC, jikwan0327 commented on src/Pages/NoticePage/NoticeDetailPage/index.tsx
> +	}, [noticeDetail]);
디버깅용 코드는 작업 후 지워주세요

2024-05-13 00:18 UTC, jikwan0327 commented on src/Pages/NoticePage/NoticeDetailPage/index.tsx
> +										></Icon>
self close 해주세요

2024-05-13 00:18 UTC, jikwan0327 commented on src/Pages/NoticePage/NoticeEditPage/index.tsx
> +									onInput={(e: any) =>
any 타입은 사용을 지양해주세요

2024-05-13 00:18 UTC, jikwan0327 commented on src/Pages/NoticePage/NoticeEditPage/style.ts
> +	overflow: scroll;
prettier 설정이 잘 되어 있는지 다시 한번 확인해주세요

2024-05-13 00:18 UTC, jikwan0327 commented on src/Pages/NoticePage/NoticeWritePage/index.tsx
> +	}, [presignedUrls]);
useEffect deps를 보니 presignedUrls state 값이 변경될 때마다 writeNotice 라는 요청을 보내는 거 같은데 제가 이해한게 맞을까요? 코드의 의도가 궁금합니다.

2024-05-13 13:55 UTC, eejx0 commented on src/Apis/Files/index.ts
> +                type: "EXTENSION_FILE",
사용 안하는데 잊어버리고 안뺐습니다,, 삭제해서 올리겠습니다

2024-05-13 13:57 UTC, eejx0 commented on src/Apis/Files/response.ts
> +    }[]
확인해보겠습니다

2024-05-13 13:59 UTC, eejx0 commented on src/Apis/Notices/index.ts
> +}
이유는 따로 없어서 useQuery 사용해서 수정하겠습니다

2024-05-13 14:17 UTC, eejx0 commented on src/Pages/NoticePage/NoticeWritePage/index.tsx
> +	}, [presignedUrls]);
네 맞습니다

2024-05-13 14:27 UTC, eejx0 commented on src/Apis/Files/index.ts
> +                type: "EXTENSION_FILE",
사용하지 않아도 되는 것 같습니다,, 삭제해서 올리겠습니다

2024-05-13 23:58 UTC, KANGYONGSU23 commented on src/Apis/Notices/request.ts
> +}
사소한 거긴 한데 들여쓰기 라인 맞춰주세요

2024-05-13 23:58 UTC, KANGYONGSU23 commented on src/Components/Notice/AttachedBox/index.tsx
> +		}
여기도 에러 처리할 때는 console 대신에 toast

2024-05-13 23:58 UTC, KANGYONGSU23 commented on src/Pages/NoticePage/NoticeEditPage/index.tsx
>  	};
url? -> url

2024-05-13 23:58 UTC, KANGYONGSU23 commented on src/Pages/NoticePage/NoticeEditPage/index.tsx
>  	};
이 함수는 다른 파일로 빼는 게 좋을 듯 합니다.
Utils에 Regex가 좋겠네요

2024-05-13 23:58 UTC, KANGYONGSU23 commented on src/Pages/NoticePage/NoticeEditPage/index.tsx
> +						</_.FileWrap> */}
사용하지 않는 코드라면 지워주세요

2024-05-14 00:48 UTC, eejx0 commented on src/Pages/NoticePage/NoticeEditPage/index.tsx
> +						</_.FileWrap> */}
파일쪽은 백엔드와 얘기가 안맞는 부분이 생겨서 백엔드쪽에서 코드를 수정하기 전까지 수정은 제목과 내용만 할 수 있도록 하고 저 코드는 주석처리하고 올리기로 했습니다

2024-05-14 02:06 UTC, JJIIIINN commented on src/Apis/Notices/index.ts
> +            const { data } = await instance.post(`/notices`, noticeData);
다른 api 파일들은 path를 하나의 변수로 관리하고 있는데 여기만 따로 명시한 이유가 있나요?

2024-05-14 02:06 UTC, JJIIIINN commented on src/Apis/Notices/index.ts
> +                console.error("notice write error:", error.message);
무슨 에러인지도 적어주면 좋을 것 같아요.

2024-05-14 02:06 UTC, JJIIIINN commented on src/Apis/Notices/index.ts
> +                console.error("notice write error:", error.message);
예를 들어 내용이 비어있습니다. 같은 메시지요.

2024-05-14 02:06 UTC, JJIIIINN commented on src/Apis/Notices/index.ts
> +                console.error("notice edit error: ", error);
위와 같음

2024-05-14 02:06 UTC, JJIIIINN commented on src/Apis/axios.ts
> +				// window.location.href = '/login';
여기는 왜 주석으로 했나요?
리프레쉬가 안 되서 이동하는 것 때문이라면 플랫폼 타입을 안 보내줘서 안 되는 거라서 그걸 고쳐야할 것 같아요.

2024-05-14 02:06 UTC, JJIIIINN commented on src/Components/Notice/AttachedBox/index.tsx
> +			document.body.removeChild(a);
다운로드는 file-saver로 구현해놨어요.
통일해주세요.

2024-05-14 02:06 UTC, JJIIIINN commented on src/Components/Notice/AttachedBox/index.tsx
> +			document.body.removeChild(a);
response도 다른 곳에서는 구조분해로 {data}로 쓰고 있어서 그것도 통일해주면 좋을 것 같아요.

2024-05-14 02:06 UTC, JJIIIINN commented on src/Pages/NoticePage/NoticeDetailPage/index.tsx
> +		}
confirm 보단 모달 쓰는 게 좋을 것 같아요.

2024-05-14 02:06 UTC, JJIIIINN commented on src/Pages/NoticePage/NoticeEditPage/style.ts
> +	overflow: scroll;
프로젝트 파일 설정으로 적용되도록 따로 설정해줘야 해요.

2024-05-14 02:06 UTC, JJIIIINN commented on src/Pages/NoticePage/NoticeWritePage/index.tsx
> +			console.log('6', presignedUrls);
console 지워주세요.

2024-05-14 02:06 UTC, JJIIIINN commented
build 터지는 것도 확인하고 고쳐주세요.

2024-05-14 04:38 UTC, jikwan0327 commented on src/Pages/NoticePage/NoticeWritePage/index.tsx
> +	}, [presignedUrls]);
그런데 presignedUrls state가 바뀔 때마다 요청을 보내는 이유가 무엇인가요?

2024-05-14 08:03 UTC, eejx0 commented on src/Apis/axios.ts
> +				// window.location.href = '/login';
이 부분은 저번에 계속 로그인이 안되는 오류가 생겨서 다른 선배님한테 여쭤봤는데 우선 이렇게 하라고 하셔서 주석처리로 해놨던거 같습니다

2024-05-14 08:08 UTC, eejx0 commented on src/Apis/Notices/index.ts
> +            const { data } = await instance.post(`/notices`, noticeData);
변수로 관리할 수 있도록 수정하겠습니다

2024-05-14 08:26 UTC, eejx0 commented on src/Apis/Notices/index.ts
> +                console.error("notice edit error: ", error);
상태코드에 맞춰서 에러 메세지를 띄우면 되나요?

2024-05-14 10:21 UTC, eejx0 commented on src/Apis/Notices/index.ts
> +                console.error("notice write error:", error.message);
상태코드로 구별해서 에러 메세지를 적어두면 되나요?

2024-05-14 10:31 UTC, eejx0 commented on src/Pages/NoticePage/NoticeWritePage/index.tsx
> +	}, [presignedUrls]);
개발 하다가 확인해야할 부분이 있어서 추가했던 것 같습니다. 없어도 무관할 것 같아서 그 부분은 삭제하도록 하겠습니다

2024-05-14 14:01 UTC, eejx0 commented on src/Pages/NoticePage/NoticeEditPage/style.ts
> +	overflow: scroll;
설정 오류가 있어서 다시 설정 완료했습니다

2024-05-29 00:02 UTC, jikwan0327 approved these changes

2024-05-30 05:33 UTC, KANGYONGSU23 approved these changes

2024-05-30 05:52 UTC, merged